### ISSUE TITLE
TypeError: Invalid descriptor for property '__symbol:toStringTag0....'

### ISSUE THREAD

**Issue by rokoroku** [Financial-Times/polyfill-library#163]
## What
Bug Report

## Details
I don't have any idea where this bug is being occurred, but my issue reporting tool keep reporting this kind of issue, only in IE:
```
TypeError '__symbol:toStringTag0.0986125710830513212' 속성에 대한 설명자가 잘못되었습니다. 
    https://cdn.polyfill.io/v3/polyfill.js:4705:4 setDescriptor
    https://cdn.polyfill.io/v3/polyfill.js:4608:4 defineProp
    https://app.closer.ai/js/6833b2cf6780d17cf89f.js:1:3680 f.r
    https://app.closer.ai/js/84549ca973e30dd8d09b.js:1:93 Anonymous function
    https://app.closer.ai/js/6833b2cf6780d17cf89f.js:1:516 f
    https://cdn.polyfill.io/v3/polyfill.js:4069:1793 g
    https://cdn.polyfill.io/v3/polyfill.js:4069:292 f
    https://cdn.polyfill.io/v3/polyfill.js:4069:4184 Anonymous function
    https://cdn.polyfill.io/v3/polyfill.js:4069:426 e
```

<details>
  <summary>Click to view full logs</summary>

![스크린샷 2019-03-19 오후 3 48 03](https://user-images.githubusercontent.com/5208632/54585786-6b5aba00-4a5e-11e9-90f6-040dc51c1ebd.png)

```
  TypeError: '__symbol:toStringTag0.632161803280279112' 속성에 대한 설명자가 잘못되었습니다.
     {
        [functions]: ,
        __proto__: { },
        __symbol:0.632161803280279131: undefined,
        __symbol:0.632161803280279132: undefined,
        __symbol:0.632161803280279133: undefined,
        __symbol:0.632161803280279134: undefined,
        __symbol:0.632161803280279135: undefined,
        __symbol:0.632161803280279136: undefined,
        __symbol:0.632161803280279137: undefined,
        __symbol:0.632161803280279143: undefined,
        __symbol:0.632161803280279146: undefined,
        __symbol:0.632161803280279147: undefined,
        __symbol:0.632161803280279156: undefined,
        __symbol:0.632161803280279170: undefined,
        __symbol:0.632161803280279179: undefined,
        __symbol:0.632161803280279180: undefined,
        __symbol:0.632161803280279181: undefined,
        __symbol:0.632161803280279182: undefined,
        __symbol:0.632161803280279187: undefined,
        __symbol:0.6321618032802791112: undefined,
        __symbol:0.6321618032802791114: undefined,
        __symbol:0.6321618032802791131: undefined,
        __symbol:0.6321618032802791132: undefined,
        __symbol:0.6321618032802791133: undefined,
        __symbol:0.6321618032802791134: undefined,
        __symbol:0.6321618032802791140: undefined,
        __symbol:0.6321618032802791214: undefined,
        __symbol:0.6321618032802791227: undefined,
        __symbol:0.6321618032802791228: undefined,
        __symbol:__symbol:react.async_mode0.6321618032802791: undefined,
        __symbol:__symbol:react.concurrent_mode0.6321618032802791: undefined,
        __symbol:__symbol:react.context0.6321618032802791: undefined,
        __symbol:__symbol:react.element0.6321618032802791: undefined,
        __symbol:__symbol:react.forward_ref0.6321618032802791: undefined,
        __symbol:__symbol:react.fragment0.6321618032802791: undefined,
        __symbol:__symbol:react.lazy0.6321618032802791: undefined,
        __symbol:__symbol:react.memo0.6321618032802791: undefined,
        __symbol:__symbol:react.portal0.6321618032802791: undefined,
        __symbol:__symbol:react.profiler0.6321618032802791: undefined,
        __symbol:__symbol:react.provider0.6321618032802791: undefined,
        __symbol:__symbol:react.strict_mode0.6321618032802791: undefined,
        __symbol:__symbol:react.suspense0.6321618032802791: undefined,
        __symbol:clipboardData0.6321618032802791157: undefined,
        __symbol:disposeOnUnmount0.632161803280279125: undefined,
        __symbol:foo0.6321618032802791135: undefined,
        __symbol:hasInstance0.63216180328027911: undefined,
        __symbol:isConcatSpreadable0.63216180328027912: undefined,
        __symbol:isForcingUpdate0.632161803280279120: undefined,
        __symbol:isUnmounted0.632161803280279118: undefined,
        __symbol:iterator0.63216180328027913: undefined,
        __symbol:joi-annotations0.632161803280279127: undefined,
        __symbol:match0.63216180328027914: undefined,
        __symbol:patchedDefinition0.632161803280279117: undefined,
        __symbol:patchMixins0.632161803280279116: undefined,
        __symbol:pending0.632161803280279126: undefined,
        __symbol:reactProp_props_atomHolder0.632161803280279122: undefined,
        __symbol:reactProp_props_atomHolder0.632161803280279139: undefined,
        __symbol:reactProp_props_atomHolder0.632161803280279149: undefined,
        __symbol:reactProp_props_atomHolder0.632161803280279153: undefined,
        __symbol:reactProp_props_atomHolder0.632161803280279158: undefined,
        __symbol:reactProp_props_atomHolder0.632161803280279162: undefined,
        __symbol:reactProp_props_atomHolder0.632161803280279166: undefined,
        __symbol:reactProp_props_atomHolder0.632161803280279172: undefined,
        __symbol:reactProp_props_atomHolder0.632161803280279176: undefined,
        __symbol:reactProp_props_atomHolder0.632161803280279184: undefined,
        __symbol:reactProp_props_atomHolder0.632161803280279189: undefined,
        __symbol:reactProp_props_atomHolder0.632161803280279193: undefined,
        __symbol:reactProp_props_atomHolder0.632161803280279197: undefined,
        __symbol:reactProp_props_atomHolder0.6321618032802791101: undefined,
        __symbol:reactProp_props_atomHolder0.6321618032802791105: undefined,
        __symbol:reactProp_props_atomHolder0.6321618032802791109: undefined,
        __symbol:reactProp_props_atomHolder0.6321618032802791116: undefined,
        __symbol:reactProp_props_atomHolder0.6321618032802791120: undefined,
        __symbol:reactProp_props_atomHolder0.6321618032802791124: undefined,
        __symbol:reactProp_props_atomHolder0.6321618032802791128: undefined,
        __symbol:reactProp_props_atomHolder0.6321618032802791137: undefined,
        __symbol:reactProp_props_atomHolder0.6321618032802791142: undefined,
        __symbol:reactProp_props_atomHolder0.6321618032802791146: undefined,
        __symbol:reactProp_props_atomHolder0.6321618032802791150: undefined,
        __symbol:reactProp_props_atomHolder0.6321618032802791154: undefined,
        __symbol:reactProp_props_atomHolder0.6321618032802791159: undefined,
        __symbol:reactProp_props_atomHolder0.6321618032802791163: undefined,
        __symbol:reactProp_props_atomHolder0.6321618032802791167: undefined,
        __symbol:reactProp_props_atomHolder0.6321618032802791171: undefined,
        __symbol:reactProp_props_atomHolder0.6321618032802791175: undefined,
        __symbol:reactProp_props_atomHolder0.6321618032802791179: undefined,
        __symbol:reactProp_props_atomHolder0.6321618032802791183: undefined,
        __symbol:reactProp_props_atomHolder0.6321618032802791187: undefined,
        __symbol:reactProp_props_atomHolder0.6321618032802791191: undefined,
        __symbol:reactProp_props_atomHolder0.6321618032802791195: undefined,
        __symbol:reactProp_props_atomHolder0.6321618032802791199: undefined,
        __symbol:reactProp_props_atomHolder0.6321618032802791203: undefined,
        __symbol:reactProp_props_atomHolder0.6321618032802791207: undefined,
        __symbol:reactProp_props_atomHolder0.6321618032802791211: undefined,
        __symbol:reactProp_props_atomHolder0.6321618032802791216: undefined,
        __symbol:reactProp_props_atomHolder0.6321618032802791220: undefined,
        __symbol:reactProp_props_atomHolder0.6321618032802791224: undefined,
        __symbol:reactProp_props_atomHolder0.6321618032802791230: undefined,
        __symbol:reactProp_props_atomHolder0.6321618032802791234: undefined,
        __symbol:reactProp_props_atomHolder0.6321618032802791238: undefined,
        __symbol:reactProp_props_atomHolder0.6321618032802791242: undefined,
        __symbol:reactProp_props_atomHolder0.6321618032802791246: undefined,
        __symbol:reactProp_props_valueHolder0.632161803280279121: undefined,
        __symbol:reactProp_props_valueHolder0.632161803280279138: undefined,
        __symbol:reactProp_props_valueHolder0.632161803280279148: undefined,
        __symbol:reactProp_props_valueHolder0.632161803280279152: undefined,
        __symbol:reactProp_props_valueHolder0.632161803280279157: undefined,
        __symbol:reactProp_props_valueHolder0.632161803280279161: undefined,
        __symbol:reactProp_props_valueHolder0.632161803280279165: undefined,
        __symbol:reactProp_props_valueHolder0.632161803280279171: undefined,
        __symbol:reactProp_props_valueHolder0.632161803280279175: undefined,
        __symbol:reactProp_props_valueHolder0.632161803280279183: undefined,
        __symbol:reactProp_props_valueHolder0.632161803280279188: undefined,
        __symbol:reactProp_props_valueHolder0.632161803280279192: undefined,
        __symbol:reactProp_props_valueHolder0.632161803280279196: undefined,
        __symbol:reactProp_props_valueHolder0.6321618032802791100: undefined,
        __symbol:reactProp_props_valueHolder0.6321618032802791104: undefined,
        __symbol:reactProp_props_valueHolder0.6321618032802791108: undefined,
        __symbol:reactProp_props_valueHolder0.6321618032802791115: undefined,
        __symbol:reactProp_props_valueHolder0.6321618032802791119: undefined,
        __symbol:reactProp_props_valueHolder0.6321618032802791123: undefined,
        __symbol:reactProp_props_valueHolder0.6321618032802791127: undefined,
        __symbol:reactProp_props_valueHolder0.6321618032802791136: undefined,
        __symbol:reactProp_props_valueHolder0.6321618032802791141: undefined,
        __symbol:reactProp_props_valueHolder0.6321618032802791145: undefined,
        __symbol:reactProp_props_valueHolder0.6321618032802791149: undefined,
        __symbol:reactProp_props_valueHolder0.6321618032802791153: undefined,
        __symbol:reactProp_props_valueHolder0.6321618032802791158: undefined,
        __symbol:reactProp_props_valueHolder0.6321618032802791162: undefined,
        __symbol:reactProp_props_valueHolder0.6321618032802791166: undefined,
        __symbol:reactProp_props_valueHolder0.6321618032802791170: undefined,
        __symbol:reactProp_props_valueHolder0.6321618032802791174: undefined,
        __symbol:reactProp_props_valueHolder0.6321618032802791178: undefined,
        __symbol:reactProp_props_valueHolder0.6321618032802791182: undefined,
        __symbol:reactProp_props_valueHolder0.6321618032802791186: undefined,
        __symbol:reactProp_props_valueHolder0.6321618032802791190: undefined,
        __symbol:reactProp_props_valueHolder0.6321618032802791194: undefined,
        __symbol:reactProp_props_valueHolder0.6321618032802791198: undefined,
        __symbol:reactProp_props_valueHolder0.6321618032802791202: undefined,
        __symbol:reactProp_props_valueHolder0.6321618032802791206: undefined,
        __symbol:reactProp_props_valueHolder0.6321618032802791210: undefined,
        __symbol:reactProp_props_valueHolder0.6321618032802791215: undefined,
        __symbol:reactProp_props_valueHolder0.6321618032802791219: undefined,
        __symbol:reactProp_props_valueHolder0.6321618032802791223: undefined,
        __symbol:reactProp_props_valueHolder0.6321618032802791229: undefined,
        __symbol:reactProp_props_valueHolder0.6321618032802791233: undefined,
        __symbol:reactProp_props_valueHolder0.6321618032802791237: undefined,
        __symbol:reactProp_props_valueHolder0.6321618032802791241: undefined,
        __symbol:reactProp_props_valueHolder0.6321618032802791245: undefined,
        __symbol:reactProp_state_atomHolder0.632161803280279124: undefined,
        __symbol:reactProp_state_atomHolder0.632161803280279141: undefined,
        __symbol:reactProp_state_atomHolder0.632161803280279151: undefined,
        __symbol:reactProp_state_atomHolder0.632161803280279155: undefined,
        __symbol:reactProp_state_atomHolder0.632161803280279160: undefined,
        __symbol:reactProp_state_atomHolder0.632161803280279164: undefined,
        __symbol:reactProp_state_atomHolder0.632161803280279168: undefined,
        __symbol:reactProp_state_atomHolder0.632161803280279174: undefined,
        __symbol:reactProp_state_atomHolder0.632161803280279178: undefined,
        __symbol:reactProp_state_atomHolder0.632161803280279186: undefined,
        __symbol:reactProp_state_atomHolder0.632161803280279191: undefined,
        __symbol:reactProp_state_atomHolder0.632161803280279195: undefined,
        __symbol:reactProp_state_atomHolder0.632161803280279199: undefined,
        __symbol:reactProp_state_atomHolder0.6321618032802791103: undefined,
        __symbol:reactProp_state_atomHolder0.6321618032802791107: undefined,
        __symbol:reactProp_state_atomHolder0.6321618032802791111: undefined,
        __symbol:reactProp_state_atomHolder0.6321618032802791118: undefined,
        __symbol:reactProp_state_atomHolder0.6321618032802791122: undefined,
        __symbol:reactProp_state_atomHolder0.6321618032802791126: undefined,
        __symbol:reactProp_state_atomHolder0.6321618032802791130: undefined,
        __symbol:reactProp_state_atomHolder0.6321618032802791139: undefined,
        __symbol:reactProp_state_atomHolder0.6321618032802791144: undefined,
        __symbol:reactProp_state_atomHolder0.6321618032802791148: undefined,
        __symbol:reactProp_state_atomHolder0.6321618032802791152: undefined,
        __symbol:reactProp_state_atomHolder0.6321618032802791156: undefined,
        __symbol:reactProp_state_atomHolder0.6321618032802791161: undefined,
        __symbol:reactProp_state_atomHolder0.6321618032802791165: undefined,
        __symbol:reactProp_state_atomHolder0.6321618032802791169: undefined,
        __symbol:reactProp_state_atomHolder0.6321618032802791173: undefined,
        __symbol:reactProp_state_atomHolder0.6321618032802791177: undefined,
        __symbol:reactProp_state_atomHolder0.6321618032802791181: undefined,
        __symbol:reactProp_state_atomHolder0.6321618032802791185: undefined,
        __symbol:reactProp_state_atomHolder0.6321618032802791189: undefined,
        __symbol:reactProp_state_atomHolder0.6321618032802791193: undefined,
        __symbol:reactProp_state_atomHolder0.6321618032802791197: undefined,
        __symbol:reactProp_state_atomHolder0.6321618032802791201: undefined,
        __symbol:reactProp_state_atomHolder0.6321618032802791205: undefined,
        __symbol:reactProp_state_atomHolder0.6321618032802791209: undefined,
        __symbol:reactProp_state_atomHolder0.6321618032802791213: undefined,
        __symbol:reactProp_state_atomHolder0.6321618032802791218: undefined,
        __symbol:reactProp_state_atomHolder0.6321618032802791222: undefined,
        __symbol:reactProp_state_atomHolder0.6321618032802791226: undefined,
        __symbol:reactProp_state_atomHolder0.6321618032802791232: undefined,
        __symbol:reactProp_state_atomHolder0.6321618032802791236: undefined,
        __symbol:reactProp_state_atomHolder0.6321618032802791240: undefined,
        __symbol:reactProp_state_atomHolder0.6321618032802791244: undefined,
        __symbol:reactProp_state_atomHolder0.6321618032802791248: undefined,
        __symbol:reactProp_state_valueHolder0.632161803280279123: undefined,
        __symbol:reactProp_state_valueHolder0.632161803280279140: undefined,
        __symbol:reactProp_state_valueHolder0.632161803280279150: undefined,
        __symbol:reactProp_state_valueHolder0.632161803280279154: undefined,
        __symbol:reactProp_state_valueHolder0.632161803280279159: undefined,
        __symbol:reactProp_state_valueHolder0.632161803280279163: undefined,
        __symbol:reactProp_state_valueHolder0.632161803280279167: undefined,
        __symbol:reactProp_state_valueHolder0.632161803280279173: undefined,
        __symbol:reactProp_state_valueHolder0.632161803280279177: undefined,
        __symbol:reactProp_state_valueHolder0.632161803280279185: undefined,
        __symbol:reactProp_state_valueHolder0.632161803280279190: undefined,
        __symbol:reactProp_state_valueHolder0.632161803280279194: undefined,
        __symbol:reactProp_state_valueHolder0.632161803280279198: undefined,
        __symbol:reactProp_state_valueHolder0.6321618032802791102: undefined,
        __symbol:reactProp_state_valueHolder0.6321618032802791106: undefined,
        __symbol:reactProp_state_valueHolder0.6321618032802791110: undefined,
        __symbol:reactProp_state_valueHolder0.6321618032802791117: undefined,
        __symbol:reactProp_state_valueHolder0.6321618032802791121: undefined,
        __symbol:reactProp_state_valueHolder0.6321618032802791125: undefined,
        __symbol:reactProp_state_valueHolder0.6321618032802791129: undefined,
        __symbol:reactProp_state_valueHolder0.6321618032802791138: undefined,
        __symbol:reactProp_state_valueHolder0.6321618032802791143: undefined,
        __symbol:reactProp_state_valueHolder0.6321618032802791147: undefined,
        __symbol:reactProp_state_valueHolder0.6321618032802791151: undefined,
        __symbol:reactProp_state_valueHolder0.6321618032802791155: undefined,
        __symbol:reactProp_state_valueHolder0.6321618032802791160: undefined,
        __symbol:reactProp_state_valueHolder0.6321618032802791164: undefined,
        __symbol:reactProp_state_valueHolder0.6321618032802791168: undefined,
        __symbol:reactProp_state_valueHolder0.6321618032802791172: undefined,
        __symbol:reactProp_state_valueHolder0.6321618032802791176: undefined,
        __symbol:reactProp_state_valueHolder0.6321618032802791180: undefined,
        __symbol:reactProp_state_valueHolder0.6321618032802791184: undefined,
        __symbol:reactProp_state_valueHolder0.6321618032802791188: undefined,
        __symbol:reactProp_state_valueHolder0.6321618032802791192: undefined,
        __symbol:reactProp_state_valueHolder0.6321618032802791196: undefined,
        __symbol:reactProp_state_valueHolder0.6321618032802791200: undefined,
        __symbol:reactProp_state_valueHolder0.6321618032802791204: undefined,
        __symbol:reactProp_state_valueHolder0.6321618032802791208: undefined,
        __symbol:reactProp_state_valueHolder0.6321618032802791212: undefined,
        __symbol:reactProp_state_valueHolder0.6321618032802791217: undefined,
        __symbol:reactProp_state_valueHolder0.6321618032802791221: undefined,
        __symbol:reactProp_state_valueHolder0.6321618032802791225: undefined,
        __symbol:reactProp_state_valueHolder0.6321618032802791231: undefined,
        __symbol:reactProp_state_valueHolder0.6321618032802791235: undefined,
        __symbol:reactProp_state_valueHolder0.6321618032802791239: undefined,
        __symbol:reactProp_state_valueHolder0.6321618032802791243: undefined,
        __symbol:reactProp_state_valueHolder0.6321618032802791247: undefined,
        __symbol:replace0.63216180328027915: undefined,
        __symbol:search0.63216180328027916: undefined,
        __symbol:singleton0.632161803280279128: undefined,
        __symbol:singleton0.632161803280279129: undefined,
        __symbol:singleton0.632161803280279130: undefined,
        __symbol:skipRender0.632161803280279119: undefined,
        __symbol:species0.63216180328027917: undefined,
        __symbol:split0.632161803280279110: undefined,
        __symbol:Symbol._hidden0.632161803280279142: undefined,
        __symbol:Symbol.asyncIterator0.632161803280279144: undefined,
        __symbol:Symbol.observable0.632161803280279145: undefined,
        __symbol:THEMR_CONFIG0.632161803280279169: undefined,
        __symbol:toPrimitive0.632161803280279111: undefined,
        __symbol:undef0.63216180328027918: undefined,
        __symbol:undef0.63216180328027919: undefined,
        __symbol:undef0.632161803280279114: undefined,
        __symbol:undef0.632161803280279115: undefined,
        __symbol:unscopables0.632161803280279113: undefined,
        __symbol:validators0.6321618032802791113: undefined,
        description: "'__symbol:toStringTag0.632161803280279112' 속성에 대한 설명자가 잘못되었습니다.",
        message: "'__symbol:toStringTag0.632161803280279112' 속성에 대한 설명자가 잘못되었습니다.",
        name: "TypeError",
        number: -2146823281,
        stack: "TypeError: '__symbol:toStringTag0.632161803280279112' 속성에 대한 설명자가 잘못되었습니다.
     at setDescriptor (https://cdn.polyfill.io/v3/polyfill.js?flags=gated&features=default,es5,es6,es7,Intl,Intl.~locale.en-US,Intl.~locale.ko-KR,Element.prototype.dataset:4705:4)
     at defineProp (https://cdn.polyfill.io/v3/polyfill.js?flags=gated&features=default,es5,es6,es7,Intl,Intl.~locale.en-US,Intl.~locale.ko-KR,Element.prototype.dataset:4608:4)
     at f.r (https://app.closer.ai/js/6833b2cf6780d17cf89f.js:1:3680)
     at Anonymous function (https://app.closer.ai/js/f1c7eba30aa09121cdc1.js:1:92)
     at f (https://app.closer.ai/js/6833b2cf6780d17cf89f.js:1:516)
     at g (https://cdn.polyfill.io/v3/polyfill.js?flags=gated&features=default,es5,es6,es7,Intl,Intl.~locale.en-US,Intl.~locale.ko-KR,Element.prototype.dataset:4069:1793)
     at f (https://cdn.polyfill.io/v3/polyfill.js?flags=gated&features=default,es5,es6,es7,Intl,Intl.~locale.en-US,Intl.~locale.ko-KR,Element.prototype.dataset:4069:292)
     }
```
</details>

### Other information
- browserName: IE
- browserVersion: 11.0.0
- locale: ko-KR
- osName: Windows 10.0
- time: 2019-03-19T05:48:29.408Z
- userAgent: Mozilla/5.0 (Windows NT 10.0; WOW64; Trident/7.0; .NET4.0C; .NET4.0E; .NET CLR 2.0.50727; .NET CLR 3.0.30729; .NET CLR 3.5.30729; rv:11.0) like Gecko

**Comment by Eugen-Ask** [comment]
I got the same bug when use React.lazy\Suspense functionality

**Comment by HenriqueLimas** [comment]
I got the same error on IE and Chrome 37 (It is easier to debug with the dev tools). In my case I am using ReactUniversalComponent for the lazy loading of the components together with Webpack.

The workaround that we did was to set in our main js a code like this

```js
Object.prototype[Symbol.toStringTag] = Object.prototype[Symbol.toStringTag]; 
```

This is set the descriptor again to the prototype for that key, since the setDescriptor ([source code](https://github.com/Financial-Times/polyfill-service/blob/1f45e5b95625180117d5b2f1979d8e217bc791a4/packages/polyfill-library/polyfills/Symbol/polyfill.js#L227)) delete it and try to set it again.

**Comment by KevinGruber** [comment]
Thx for the working workaround! 👍 

But is there a "real" solution planned for that?
I don't think that everybody should have to add that "Workaround" to his or her application.
